[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ccxt>=4.5.10",
    "flask>=3.1.2",
    "numpy>=2.3.3",
    "requests>=2.32.5",
]
